# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Raf Book List with API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SwiftyJSON'
  # Pods for Raf Book List with API

end
